engines:
  eslint:
    enabled: true
    checks:
      import/extensions:
        enabled: false
ratings:
   paths:
   - server/**
   - config/**
   - "**.js"
exclude_paths:
- node_modules/**/*
- server/tests/**
