language: node_js
node_js:
  - "4.8"
  - "6.10"
  - "7.6"
services:
  - mongodb
cache:
  directories:
  - node_modules
git:
  depth: 3
script:
  - yarn test:check-coverage
after_script:
  - yarn report-coverage
before_deploy: yarn run build
deploy:
  provider: heroku
  api_key: 2adfeb9f-36bb-4565-b998-1fdf2f576032
  app: keepo-api
  on:
    repo: pathe-planner/pathe-server
  skip_cleanup: true